ALTER TABLE
    SYS_APP_LEVEL_SETUP ADD (SMS_FLAG INTEGER DEFAULT 0);
ALTER TABLE
    SYS_APP_LEVEL_SETUP ADD (SHOW_DETAIL_FLAG INTEGER DEFAULT 0);
COMMENT ON COLUMN SYS_APP_LEVEL_SETUP.SMS_FLAG
    IS '短信提醒标识(0：否，1：是)';
COMMENT ON COLUMN SYS_APP_LEVEL_SETUP.SHOW_DETAIL_FLAG
    IS '展示详细信息标识(0：否，1：是)';

ALTER TABLE
    SYS_APP_MANAGE_CONTACT_WAY ADD (KEY_WORD VARCHAR2(200));
COMMENT ON COLUMN SYS_APP_MANAGE_CONTACT_WAY.KEY_WORD
IS '接收关键字';
