--初始化贷前数据字典的脚本
declare
  dictid number:=0;     
begin

  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_SUPPLYSTATE','回复信息状态', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'超时','0', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'待补件','1', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'补件完成','2', '3', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CUSTOMERTYPE','客户类型', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'黑名单','6', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'老客户','3', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'客户','2', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'储备客户','1', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'竞争对手','5', '5', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'合作伙伴','4', '6', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_COMPLAINTTYPE','投诉分类', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','9', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'催收情况','3', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'服务态度','1', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'审批情况','2', '4', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_COMPLAINTSTATE','投诉单状态', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'处理中','2', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'已处理','3', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'审核中','4', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'待处理','1', '4', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_COMPLAINTPROCESS','投诉处理结果', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'已解决','2', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'未解决','1', '2', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_COMPLAINTAUDIT','投诉审核结果', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'同意','1', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'拒绝','2', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'回退','3', '3', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_SERVICEMODE','服务方式', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'电访','1', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'外访','2', '2', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_SERVICETYPE','服务类型', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'咨询','1', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'建议','2', '2', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_LOAN_TYPE','贷款种类', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'同业','4', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'房贷','0', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'车贷','1', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'助学贷','3', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','2', '5', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CREDIT_INVEST_STATUS','贷款类型', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'房贷','0', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'车贷','1', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'经营型贷款','2', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'个人消费贷','3', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'担保','5', '5', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其它','4', '6', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_APPROVEATTACHMENT','附件审核附件', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'资产证明','18', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'居住证明','16', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'社保证明','21', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'身份证明','13', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'学历证明','22', '5', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'在校生证明','23', '6', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'企业证明','17', '7', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'工作证明','15', '8', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'SALESMANLEVEL','业务员分类', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'A类','A', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'B类','B', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'C类','C', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'D类','D', '4', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CUSTOMERTYPE','产品客群分类', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'D','D', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'C','C', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'B','B', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'A','A', '4', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_PRIVATEAPPROVES','企业信息', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'合作及订货协议','5', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','6', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'经营场所地址证明','4', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'经营场所','3', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'股权证明','2', '5', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'营业执照','1', '6', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_PRIVCOMPOHTERFUND','企业其他资产', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'自有车辆','0', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'自有房产','1', '2', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CREDITSTATUS','信用情况', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'账户状态不良','1', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'当前逾期','0', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其它不良情况','5', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'正常','4', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'历史逾期(超过90天)','3', '5', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'历史逾期(90天内)','2', '6', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','3', '7', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'到期一次性偿还贷款','2', '8', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'信用贷款','1', '9', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_COMPANYOWNERRELATION','借款人与其他股东关系', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'旁系亲属','2', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'朋友','3', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','4', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'直系亲属','1', '4', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CREDITCONTRACT','借款合同', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'借款合同','5', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'咨询协议','3', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'借款协议','0', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'服务协议','1', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'风险金协议','2', '5', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'委托扣款授权书','4', '6', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE00','借款用途', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'消费','1', '1', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE01','借款用途_消费', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'购物','101', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'装修','103', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'培训','102', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'旅游','104', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'结婚','105', '5', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE00','借款用途', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'实体经营','2', '1', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE02','借款用途_实体经营', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'扩大经营','203', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'实体经营','201', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'进货','202', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'发工资','203', '4', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE00','借款用途', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'金融投资','3', '1', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE03','借款用途_金融投资', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'理财产品','302', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'证券','301', '2', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE00','借款用途', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'敏感用途','4', '1', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE04','借款用途_敏感用途', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'医疗费用','401', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'博彩类','406', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'还信用卡','403', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'还贷款','404', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'为他人借款','405', '5', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'还他人钱','402', '6', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE00','借款用途', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','5', '1', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE05','借款用途_其他', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','501', '1', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE00','借款用途', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'购房','6', '1', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE06','借款用途_购房', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'购房','601', '1', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE00','借款用途', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'购车','7', '1', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_REQUESTUSE07','借款用途_购车', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'购车','701', '1', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_EXPLOREANALYSIS','分析项目', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'市场行业情况分析','3', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'信用记录及负债情况','2', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'企业经营风险','4', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'销售额、成本、支出、利润分析','1', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'客户家庭情况及资产情况','0', '5', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_URGENTTYPE','加急状态', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'普通件','FALSE', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'收费加急','true1', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'免费加急','true2', '3', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CUSTOMERTYPE1','客户类型1（流水）', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'高端贷有房','0', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'高端贷无房','1', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'工薪现金发薪无房','5', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'工薪现金发薪有房','4', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'工薪贷有房','2', '5', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'工薪贷无房','3', '6', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CUSTOMERTYPE3','客户类型3（流水）', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'经营贷有房','0', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'经营贷无房','1', '2', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CUSTOMERTYPE4','客户类型4（流水）', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'助楼贷','0', '1', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_VISIT_CONTENT','外访内容', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'家访外访表','1', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'特许证','2', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'外访照片','3', '3', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CHECKADDRESS','核对单位地址', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'被调查人不清楚','4', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'基本一致','3', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'一致','1', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'不一致','2', '4', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CHECKPHONE','核对单位电话', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'被调查人不清楚','4', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'基本一致','3', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'一致','1', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'不一致','2', '4', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CHECKJOB','核对工作情况', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'被调查人不清楚','4', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'不一致','3', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'一致','1', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'基本一致','2', '4', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CHECKJOBTIME','核对工作时间', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'被调查人不清楚','2', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'知晓','1', '2', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CHECKPROPERTY','核对房产', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'被调查人不清楚','5', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'与父母同住','4', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'租房','3', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'无','2', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'有','1', '5', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CHECKINCOME','核对收入', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'被调查人不清楚','2', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'知晓','1', '2', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_EXPLOREOBJECT','调查对象', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'路人','0', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'厂长','3', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'门卫','1', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'工人','4', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'客户本人','2', '5', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_SURVEYPHASE','调查阶段', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'调查失败','4', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'完成调查','3', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'正在调查','2', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'未调查','1', '4', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_EXPLOREPROJECT','调查项目', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'从业人数','1', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'增值税','6', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'生产线','3', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'企业合作合同','7', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'应收应付','8', '5', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'办公区域','2', '6', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'纳税申报表','5', '7', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'仓库情况','4', '8', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'经营费用','9', '9', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'环境调查','0', '10', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_PASSCODE','通过代码', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'A104','A104', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'A0910','A0910', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'A0521','A0521', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'A103','A103', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'A101','A101', '5', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'A0521_2','A0521_2', '6', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'A0521_1','A0521_1', '7', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'A0521_3','A0521_3', '8', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'A102','A102', '9', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'A1111','A1111', '10', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'OVERDUETRANSFERCODE','催收案件移交代码', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'未逾期案件（风险案件）提前移交','E', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'客户发生骗贷、逃匿、死亡、入狱、被执行、冒办、盗办等情形的','D', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'客户连续3次违背付款承诺，未依约定日期、金额还款的','C', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'连续3天未能联系到客户本人，且家人无代偿意愿的','A', '4', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'连续跟进15天，客户无还款记录亦无承诺还款的','B', '5', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CREDITTYPE','征信版本类型', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'精版','0', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'简版','1', '2', '1', null); 
  dictid:=0;
  select seq_sys_dict.nextval into dictid from dual;
  insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DQ_CUSTOMERSOURCE','客户来源', '1', '1', null) ;
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'网络','2', '1', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'朋友介绍','3', '2', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','9', '3', '1', null); 
  insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'报纸','1', '4', '1', null); 
  commit; 
  end; 
