--初始化系统数据字典的脚本
begin
declare
	dictid number:=0;     
begin

	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'IDTYPE','证件类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'护照','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'户口簿','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'港澳台居民往来大陆通行证','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'军官证','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'身份证','1', '1', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'SEX','性别', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'男','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'女','0', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','9', '3', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'EDUCATION','学历', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'本科','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'硕士及以上','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'专科','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'初中及以下','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'高中','4', '4', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'YESNO','是否', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'否','0', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'是','1', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'MARITALSTATUS','婚姻状况', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'已婚','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'离异','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'丧偶','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'未婚','1', '1', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'COMPANYTYPE','企业类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'个体工商户','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'股份有限公司','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'有限责任公司','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'合伙','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'独资','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','6', '6', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'UNITNATURE','工作单位性质', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'三资企业','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'机关及事业单位','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'国营','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'民营','3', '3', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'WORKYEAR','工作年限', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'1年以下','0', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'1（含）-2年','1', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'2（含）-5年','2', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'5（含）以上','3', '4', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'COMPANYSCALE','单位规模', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'100人以下','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'3000人以上','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'1000-3000人','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'500-1000人','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'100-500人','2', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'HOUSETYPE','住宅类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'无按揭购房','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'亲属住房','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'租房','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'公积金按揭购房','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'商业按揭购房','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'单位宿舍','7', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','8', '8', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'自建房','6', '6', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'ESTATETYPE','房产类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'全款房','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'公积金按揭房','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'商业按揭房','2', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'ADDRTYPE','地址类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'家庭地址','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'户籍地址','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'联系地址','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'单位地址','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'发证机关地址','5', '5', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'CHILDSTATUS','子女现状', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'婴幼儿','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'小学','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'工作','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'大学','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'中学','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','9', '6', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'JOBNATURE','工作性质', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'试用/临时','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'正式职员','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'企业主/股东','1', '1', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'PAYWAGE','工资发放方式', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'转账打卡','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'转账打卡+现金','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'现金','2', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'PRIORITY','优先级', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'中','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'高','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'低','3', '3', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'URGENCY','紧急程度', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'普通','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'非常紧急','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'紧急','2', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'CUSTOMERSATISFACTION','客户满意度', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'非常满意','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'满意','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'一般','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'不满意','4', '4', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'CUSTOMERHOPE','客户购买意愿', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'非常有意向','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'比较有意向','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'一般需要继续了解','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'可能性较小或尚未明确情况','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'可能性极小或不可能','5', '5', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'HEALTHSTATUS','健康状况', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'良好','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'好','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'一般','3', '3', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'CENSUSTYPE','户籍种类', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'本埠农村','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'本埠城镇','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'外埠农村','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'外埠城镇','3', '3', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'HOUSERIGHT','产权性质', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'大产权','8', '8', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'宅基地','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'土地证','7', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'经济适用房','6', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'公租房','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'期房','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'小产权','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'自建房','2', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'INDUSTRYTYPE','所属行业', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'环境和公共设施管理业','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'电力、热力、燃气及水的生产和供应业','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'制造业','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'批发和零售业','9', '9', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'农、林、牧、渔业','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'综合（含投资类、主业不明显）','10', '10', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其它','11', '11', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'建筑业','6', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'交通运输、仓储业和邮政业','7', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'信息传输、计算机服务和软件业','8', '8', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'采矿业','2', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'WARRANTTYPE','担保方式', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'信用','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'抵押','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'票据','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'个人/机构担保','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','9', '5', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'INCOMESOURCE','收入来源', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'每月工资','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他收入','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'父母支付生活费','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'房屋出租','2', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'INCOMLEVEL','收入水平', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'（月薪）1万以下','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'（月薪）3万以上','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'（月薪）2万-3万','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'（月薪）1万-2万','3', '3', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'TELTYPE','电话类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'户籍联系电话','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'传真','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'手机','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'家庭电话','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'单位电话','2', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'POROOM','经营场所', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'自有房产','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'租用','1', '1', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'OCCUPATION','职业', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'自营业主','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'自由职业者','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'离/退休人员','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'公司职员','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','6', '6', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'DUTY','职务', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'初级管理人员','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'中层管理人员','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'次高层管理人员','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'高层管理人员','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'普通员工','5', '5', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'TITLE','职称', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'高级职称','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'中级职称','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'初级职称','3', '3', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'RELATIONTYPE','联系人与客户关系', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'同事','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'配偶','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'父亲','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'母亲','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'同学','7', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'朋友','6', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他亲属','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','8', '8', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'子女','9', '9', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'LINKMANTYPE','联系人类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'紧急联系人','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'联系人','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'家庭联系人','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'工作联系人','4', '4', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'CONTACTTYPE','联系方式', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','9', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'传真','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'QQ','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'邮件','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'电话','1', '1', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'LANGUAGE','语言', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'汉语','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'英语','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'日语','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'韩语','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'法语','5', '5', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'PAYFREQUENCY','还款频率', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'一次性','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'双周','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'月度','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'季度','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'半年','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'年度','6', '6', '1', null); 

	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'ACCOUNTTYPE','银行账户类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'银行卡','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'存折','2', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'BLACKLISTTYPE','黑名单类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'客户','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'企业名称','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'证件号码','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'电话','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'地址','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'电子邮件','6', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'员工','7', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'权证','8', '8', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'COMPREGMONEY','企业注册资本金（万元）', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'20万（含）-100万','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'100万（含）-300万','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'20万以下','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'300万（含）以上','0', '0', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'COMPANYAGE','公司成立时长', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'3年','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'2年','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'1年','0', '0', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'4（含）-6年','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'大于6年（含）','4', '4', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'RESIDEAPPROVE','居住证明', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'居住证明','7', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'租房合同','6', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'信用卡邮寄函','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'固话单','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'水电煤气','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'使用权证','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'房产证','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','8', '8', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'JOBTYPE','工作方式', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'雇佣','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'自营','2', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'WORKAPPROVE','工作证明', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'工作证','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'工牌','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'劳动合同','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'工作证明','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','5', '5', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'LISTENRESULT','接听情况', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'空号','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'接通','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'关机','6', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'线路故障','7', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'无人接','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'拒接','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'停机','3', '3', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'COMPLASTRATAL','最近1年企业纳税额', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'20（含）-30万','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'30（含）-50万','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'大于等于50万','0', '4', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'COMPRENTAL','月办公场地租金', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'小于2000元','0', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'4000（含）-8000','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'8000（含）以上','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'2000（含）-4000','1', '4', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'HOUSENUMBER','本地自有房产', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'2套','1', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'1套','0', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'3套及以上','2', '3', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'FYNETTYPE','法院网查询类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'终止','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'中止执行','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'执行中案件','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'无信息','0', '0', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'已结案','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其它','5', '5', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'COMMONLIVE','共同居住者', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'朋友','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','16', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'独居','8', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'配偶及子女','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'父母','1', '1', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'COMPANYINBANK','申请人流水在银行的交易情况', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'均有','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'对公','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'个人','1', '1', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'SOCIALAPPROVE','社保证明', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'完税证明','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'公积金缴纳证明','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'社保缴纳证明','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','4', '4', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'RIGHTFILEAPPROVE','股权证明文件', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'股权证明','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'验资报告','1', '1', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'OWNCARVALUE','自有车辆价值', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'30万以上','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'15万（含）以下','0', '0', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'15-30万（含）','1', '1', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'LOANACCOUNTSTATE','贷款账户状态', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'正常','0', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'抵债','3', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'结清','4', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'结束','5', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'逾期','1', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'代还','2', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','7', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'未知','6', '8', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'ASSETTPE','资产类别', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其它','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'房产','0', '0', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'保单','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'车辆','1', '1', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'ASSETAPPROVE','资产证明', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'有价证券','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'房屋抵押合同','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'房产','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'车产','2', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'IDENTITYAPPROVE','身份证明', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','6', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'结婚证','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'离婚证','7', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'身份证','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'军官证','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'户口本','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'护照','4', '4', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'MARITALHERJOB','配偶工作情况', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'在职','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'自营','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'务农','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'退休','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'无业','5', '5', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'CUSTOMERLEVEL','客户级别', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'四星级','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'三星级','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'五星级','1', '1', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'CUSTCHANNEL','客户渠道', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'58同城','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'本司','0', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'CUSTCATEGORY','客户类别', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'个人','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'单位','2', '2', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'MONEYTYPE','币种', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'人民币','CNY', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'美元','USD', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'欧元','EUR', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'日元','JPY', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'英镑','GBP', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'港币','HKD', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'澳元','AUD', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'新台币','TWD', '8', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'PAYMENTTYPE','付款方式', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'委托划扣','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'POS刷卡','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'转账','3', '3', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'LOANPURPOSE','借款用途', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'资金周转','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'购原材料','5', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'装修家居','6', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他','7', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'教育支出','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'购生活品','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'旅游','4', '4', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'POLISTATUS','政治面貌', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'党员','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'团员','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'群众','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'民主党派','4', '4', '1', null); 
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'NATION','民族', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'汉族','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'回族','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'满族','3', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'蒙古族','4', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'苗族','5', '5', '1', null);
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'壮族','6', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'维吾尔族','7', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'朝鲜族','8', '8', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'藏族','9', '9', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他少数民族','10', '10', '1', null);
	
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'PERIODTYPE','期限类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'日','1', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'月','2', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'年','3', '3', '1', null); 
	
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'SYSTEMFLAG','系统标识', '0', '1', null) ;
	
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'捷越联合贷款系统','S001', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'捷越联合理财系统','S002', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'捷越联合主数据系统','S003', '3', '1', null);
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'捷越联合合作机构管理系统','S004', '4', '1', null); 
    insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'捷越联合核心账务系统','S005', '5', '1', null); 
    insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'捷越联合核心账务系统日终','S006', '6', '1', null);
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'第三方系统','S099', '99', '1', null); 

	
	
	
	
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'COSTCODE','费用类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'服务费','F001', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'停车费','F002', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'GPS安装费','F003', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'GPS拆卸费','F004', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'抵押登记费','F005', '5', '1', null);
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'公证费','F006', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'其他费用','F999', '7', '1', null); 
	
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'PT_ROLETYPE','角色类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'工作流角色','2', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'系统角色','0', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'普通角色','1', '2', '1', null);
	
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'PT_ORGTYPE','机构类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'组织','org', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'部门','dept', '2', '1', null); 
	
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'PT_USERJOB','职务', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'部门经理','manager', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'员工','staff', '2', '1', null); 
	
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'PT_MSGSTATUS','消息状态', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'初始','0', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'生效','1', '2', '1', null);
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'失效','2', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'删除','3', '4', '1', null);
	
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'PT_MSGFLAG','消息紧急标识', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'普通','0', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'紧急','1', '2', '1', null);
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'特急','2', '3', '1', null); 

	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'PT_MSGTYPE','消息类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'全局消息','0', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'专有消息','1', '2', '1', null);
	
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'PT_USERTYPE','用户类型', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'用户','user', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'机构','org', '2', '1', null);
	
	commit; 
  end; 
  ---新增脚本
declare
	dictid number:=0;     
begin
  dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'LOANPERIODS','贷款期数', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'1期','1', '0', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'2期','2', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'3期','3', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'4期','4', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'5期','5', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'6期','6', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'12期','12', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'18期','18', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'24期','24', '8', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'36期','36', '9', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'48期','48', '10', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'30天','30', '11', '1', null); 
commit;
end;


declare
	dictid number:=0;     
begin
  dictid:=0;
  	delete from sys_dict_detail a where a.dict_id in(select id from sys_dict where dict_code='LOANFUNDS');
	delete from sys_dict where dict_code='LOANFUNDS';
	commit;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'LOANFUNDS','放款机构', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'E贷','ED', '0', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'有利网','YLW', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'向上','XS', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'正大','ZD', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'铜板街','TBJ', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'新天','XT', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'财客','CK', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'挖财','WC', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'安家世行','AJSX', '8', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'捷越','JY', '9', '1', null); 

	 dictid:=0;
	 select seq_sys_dict.nextval into dictid from dual;
	 insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE, VALIDATE_STATE, VERSION) values (dictid, 'PUNITIVECALCULATION', '罚息计算方式', '1', '1', null);
	 insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION)         values (seq_sys_dict_detail.nextval, dictid, '期限梯次计算法', '01', '1', '1', null);
	 insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION)         values (seq_sys_dict_detail.nextval, dictid, '分项分期计数法', '02', '2', '1', null);
	 
	 dictid:=0;
	 select seq_sys_dict.nextval into dictid from dual;
	 insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE, VALIDATE_STATE, VERSION) values (dictid, 'PENALTYCALCULATION', '违约金计算方式', '1', '1', null);
	 insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION)         values (seq_sys_dict_detail.nextval, dictid, '分期计算法', '01', '1', '1', null);
	 
	 dictid:=0;
     select seq_sys_dict.nextval into dictid from dual;
     insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE, VALIDATE_STATE, VERSION) values (dictid, 'CM_REPAYMENTWAY', '还款方式', '1', '1', null);
     insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION)         values (seq_sys_dict_detail.nextval, dictid, '等额本息', 'AC10001', '1', '1', null);
     insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid, '先息后本', 'AC10002', '2', '1', null);
     insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION)         values (seq_sys_dict_detail.nextval, dictid, '车贷1期', 'AC10003', '3', '1', null);
	 commit;
	 
	 dictid:=0;
     select seq_sys_dict.nextval into dictid from dual;
     insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE, VALIDATE_STATE, VERSION) values (dictid, 'CUSTOMERSOURCE', '客户来源', '1', '1', null);
     insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION)         values (seq_sys_dict_detail.nextval, dictid, '市场活动', '1', '1', '1', null);
     insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) 		   values (seq_sys_dict_detail.nextval, dictid, 'coldcall', '2', '2', '1', null);
     insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) 		   values (seq_sys_dict_detail.nextval, dictid, '理财经理自由资源', '3', '3', '1', null);
     insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) 		   values (seq_sys_dict_detail.nextval, dictid, '宣传媒体', '4', '4', '1', null);
     insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) 		   values (seq_sys_dict_detail.nextval, dictid, '老客户续投', '5', '5', '1', null);
     insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) 		   values (seq_sys_dict_detail.nextval, dictid, '员工推荐', '6', '6', '1', null);
     insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) 		   values (seq_sys_dict_detail.nextval, dictid, '老客户推荐', '7', '7', '1', null);
     insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) 		   values (seq_sys_dict_detail.nextval, dictid, '其他', '8', '8', '1', null);
	 commit;
	 
	delete from sys_dict_detail a where a.dict_id in(select id from sys_dict where dict_code='BANKCODE');
	delete from sys_dict where dict_code='BANKCODE';
	commit;
	dictid:=0;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'BANKCODE','银行名称', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'工商银行','102', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'农业银行','103', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'中国银行','104', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'建设银行','105', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'招商银行','308', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'交通银行','301', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'邮政储蓄银行','403', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'广发银行','306', '8', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'兴业银行','309', '9', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'广州银行','04135810', '10', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'光大银行','303', '11', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'民生银行','305', '12', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'浦发银行','310', '13', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'中信银行','302', '14', '1', null);
	commit; 
end;

declare
	dictid number:=0;     
begin
  dictid:=0;
  	delete from sys_dict_detail a where a.dict_id in(select id from sys_dict where dict_code='LOANPERIODS');
	delete from sys_dict where dict_code='LOANPERIODS';
	commit;
	select seq_sys_dict.nextval into dictid from dual;
	insert into sys_dict (ID, DICT_CODE, DICT_NAME, DICT_TYPE,VALIDATE_STATE, VERSION) values (dictid,'LOANPERIODS','贷款期数', '0', '1', null) ;
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'1期','1', '0', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'2期','2', '1', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'3期','3', '2', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'4期','4', '3', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'5期','5', '4', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'6期','6', '5', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'9期','9', '6', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'12期','12', '7', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'18期','18', '8', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'24期','24', '9', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'36期','36', '10', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'48期','48', '11', '1', null); 
	insert into sys_dict_detail (ID, DICT_ID, DICT_DETAIL_NAME, DICT_DETAIL_VALUE, ORDER_BY, VALIDATE_STATE, VERSION) values (seq_sys_dict_detail.nextval, dictid,'30天','30', '12', '1', null); 
commit;
end;
end;
/
