/** SYS_ORG **/
ALTER TABLE SYS_ORG ADD ORG_LEVEL  NUMBER(2);
ALTER TABLE SYS_ORG ADD EFFECTIVE_DATE   TIMESTAMP(6);
ALTER TABLE SYS_ORG ADD CREATE_TIME   TIMESTAMP(6);
comment on column SYS_ORG.ORG_LEVEL
  is '层级';
comment on column SYS_ORG.EFFECTIVE_DATE
  is '生效期';
  comment on column SYS_ORG.CREATE_TIME
  is '创建日期';

/** SYS_ORG_HIS **/
ALTER TABLE SYS_ORG_HIS ADD ORG_LEVEL  NUMBER(2);
ALTER TABLE SYS_ORG_HIS ADD EFFECTIVE_DATE   TIMESTAMP(6);
comment on column SYS_ORG_HIS.ORG_LEVEL
  is '层级';
comment on column SYS_ORG_HIS.EFFECTIVE_DATE
  is '生效期';
  
/** SYS_ORG_SYN **/
ALTER TABLE SYS_ORG_SYN ADD ORG_LEVEL  NUMBER(2);
ALTER TABLE SYS_ORG_SYN ADD EFFECTIVE_DATE   TIMESTAMP(6);
comment on column SYS_ORG_SYN.ORG_LEVEL
  is '层级';
comment on column SYS_ORG_SYN.EFFECTIVE_DATE
  is '生效期';

/** SYS_ORG_USER **/
ALTER TABLE SYS_ORG_USER ADD POSITION_CODE  VARCHAR2(50);
comment on column SYS_ORG_USER.POSITION_CODE
  is '岗位编码';

/** SYS_ORG_USER_HIS **/
ALTER TABLE SYS_ORG_USER_HIS ADD POSITION_CODE  VARCHAR2(50);
comment on column SYS_ORG_USER_HIS.POSITION_CODE
  is '岗位编码';

/** SYS_ORG_USER_SYN **/
ALTER TABLE SYS_ORG_USER_SYN ADD POSITION_CODE  VARCHAR2(50);
comment on column SYS_ORG_USER_SYN.POSITION_CODE
  is '岗位编码';
  
/** SYS_POSITION **/
ALTER TABLE SYS_POSITION ADD CREATE_DATE TIMESTAMP(6);
ALTER TABLE SYS_POSITION ADD ORG_CODE  VARCHAR2(20);
ALTER TABLE SYS_POSITION ADD IS_RESPONSIBLE    NUMBER(2);
ALTER TABLE SYS_POSITION ADD POSITION_SEQUENCE NUMBER(2);
ALTER TABLE SYS_POSITION ADD POST              VARCHAR2(50);
ALTER TABLE SYS_POSITION ADD EFFECTIVE_DATE    TIMESTAMP(6);
ALTER TABLE SYS_POSITION ADD PARENT_ID         VARCHAR2(19);
comment on column SYS_POSITION.CREATE_DATE
  is '创建时间';
comment on column SYS_POSITION.ORG_CODE
  is '所属机构编码';
comment on column SYS_POSITION.IS_RESPONSIBLE
  is '是否负责,1是,0否';
comment on column SYS_POSITION.POSITION_SEQUENCE
  is '岗位序列,1管理序列,2职能序列,3业务序列,4技术序列,5运营序列';
comment on column SYS_POSITION.POST
  is '职位';
comment on column SYS_POSITION.EFFECTIVE_DATE
  is '有效日期';
  
  /** SYS_POSITION_HIS **/
ALTER TABLE SYS_POSITION_HIS ADD ORG_CODE  VARCHAR2(20);
ALTER TABLE SYS_POSITION_HIS ADD IS_RESPONSIBLE    NUMBER(2);
ALTER TABLE SYS_POSITION_HIS ADD POSITION_SEQUENCE NUMBER(2);
ALTER TABLE SYS_POSITION_HIS ADD POST              VARCHAR2(50);
ALTER TABLE SYS_POSITION_HIS ADD EFFECTIVE_DATE    TIMESTAMP(6);

comment on column SYS_POSITION_HIS.ORG_CODE
  is '所属机构编码';
comment on column SYS_POSITION_HIS.IS_RESPONSIBLE
  is '是否负责,1是,0否';
comment on column SYS_POSITION_HIS.POSITION_SEQUENCE
  is '岗位序列,1管理序列,2职能序列,3业务序列,4技术序列,5运营序列';
comment on column SYS_POSITION_HIS.POST
  is '职位';
comment on column SYS_POSITION_HIS.EFFECTIVE_DATE
  is '有效日期';

/** SYS_POSITION_SYN **/
ALTER TABLE SYS_POSITION_SYN ADD ORG_CODE  VARCHAR2(20);
ALTER TABLE SYS_POSITION_SYN ADD IS_RESPONSIBLE    NUMBER(2);
ALTER TABLE SYS_POSITION_SYN ADD POSITION_SEQUENCE NUMBER(2);
ALTER TABLE SYS_POSITION_SYN ADD POST              VARCHAR2(50);
ALTER TABLE SYS_POSITION_SYN ADD EFFECTIVE_DATE    TIMESTAMP(6);

comment on column SYS_POSITION_SYN.ORG_CODE
  is '所属机构编码';
comment on column SYS_POSITION_SYN.IS_RESPONSIBLE
  is '是否负责,1是,0否';
comment on column SYS_POSITION_SYN.POSITION_SEQUENCE
  is '岗位序列,1管理序列,2职能序列,3业务序列,4技术序列,5运营序列';
comment on column SYS_POSITION_SYN.POST
  is '职位';
comment on column SYS_POSITION_SYN.EFFECTIVE_DATE
  is '有效日期';




/** SYS_USER **/
ALTER TABLE SYS_USER ADD PROBATION_PERIOD NUMBER(2);
ALTER TABLE SYS_USER ADD ENTRY_DATE       TIMESTAMP(6);
ALTER TABLE SYS_USER ADD QUIT_DATE        TIMESTAMP(6);
ALTER TABLE SYS_USER ADD WORK_DATE        TIMESTAMP(6);
ALTER TABLE SYS_USER ADD POLITICAL_STATUS NUMBER(2);
ALTER TABLE SYS_USER ADD USER_RELATION    NUMBER(2);
ALTER TABLE SYS_USER ADD CREATE_DATE      TIMESTAMP(6);
ALTER TABLE SYS_USER ADD CARD_NO          VARCHAR2(20);

comment on column SYS_USER.CREATE_DATE
  is '创建日期';
comment on column SYS_USER.CARD_NO
  is '证件号码';
comment on column SYS_USER.PROBATION_PERIOD
  is '试用期';
comment on column SYS_USER.ENTRY_DATE
  is '入职日期';
comment on column SYS_USER.QUIT_DATE
  is '离职日期';
comment on column SYS_USER.WORK_DATE
  is '参加工作日期';
comment on column SYS_USER.POLITICAL_STATUS
  is '政治面貌,1党员,2团员,3群众,4民主党派,5预备党员';
comment on column SYS_USER.USER_RELATION
  is '员工关系,1正式,2试用,3实习,4劳务派遣';

/** SYS_USER_HIS **/
ALTER TABLE SYS_USER_HIS ADD CARD_NO          VARCHAR2(20);
ALTER TABLE SYS_USER_HIS ADD PROBATION_PERIOD NUMBER(2);
ALTER TABLE SYS_USER_HIS ADD ENTRY_DATE       TIMESTAMP(6);
ALTER TABLE SYS_USER_HIS ADD QUIT_DATE        TIMESTAMP(6);
ALTER TABLE SYS_USER_HIS ADD WORK_DATE        TIMESTAMP(6);
ALTER TABLE SYS_USER_HIS ADD POLITICAL_STATUS NUMBER(2);
ALTER TABLE SYS_USER_HIS ADD USER_RELATION    NUMBER(2);

comment on column SYS_USER_HIS.CARD_NO
  is '证件号码';
comment on column SYS_USER_HIS.PROBATION_PERIOD
  is '试用期';
comment on column SYS_USER_HIS.ENTRY_DATE
  is '入职日期';
comment on column SYS_USER_HIS.QUIT_DATE
  is '离职日期';
comment on column SYS_USER_HIS.WORK_DATE
  is '参加工作日期';
comment on column SYS_USER_HIS.POLITICAL_STATUS
  is '政治面貌,1党员,2团员,3群众,4民主党派,5预备党员';
comment on column SYS_USER_HIS.USER_RELATION
  is '员工关系,1正式,2试用,3实习,4劳务派遣';

/** SYS_USER_SYN **/
ALTER TABLE SYS_USER_SYN ADD CARD_NO          VARCHAR2(20);
ALTER TABLE SYS_USER_SYN ADD PROBATION_PERIOD NUMBER(2);
ALTER TABLE SYS_USER_SYN ADD ENTRY_DATE       TIMESTAMP(6);
ALTER TABLE SYS_USER_SYN ADD QUIT_DATE        TIMESTAMP(6);
ALTER TABLE SYS_USER_SYN ADD WORK_DATE        TIMESTAMP(6);
ALTER TABLE SYS_USER_SYN ADD POLITICAL_STATUS NUMBER(2);
ALTER TABLE SYS_USER_SYN ADD USER_RELATION    NUMBER(2);

comment on column SYS_USER_SYN.CARD_NO
  is '证件号码';
comment on column SYS_USER_SYN.PROBATION_PERIOD
  is '试用期';
comment on column SYS_USER_SYN.ENTRY_DATE
  is '入职日期';
comment on column SYS_USER_SYN.QUIT_DATE
  is '离职日期';
comment on column SYS_USER_SYN.WORK_DATE
  is '参加工作日期';
comment on column SYS_USER_SYN.POLITICAL_STATUS
  is '政治面貌,1党员,2团员,3群众,4民主党派,5预备党员';
comment on column SYS_USER_SYN.USER_RELATION
  is '员工关系,1正式,2试用,3实习,4劳务派遣';
  
ALTER TABLE SYS_USER ADD(ANNUAL_LEAVE NUMBER(2));
comment on column SYS_USER.ANNUAL_LEAVE is '标准年假';

ALTER TABLE SYS_USER_HIS ADD(ANNUAL_LEAVE NUMBER(2));
comment on column SYS_USER_HIS.ANNUAL_LEAVE is '标准年假';

ALTER TABLE SYS_USER_SYN ADD(ANNUAL_LEAVE NUMBER(2));
comment on column SYS_USER_SYN.ANNUAL_LEAVE is '标准年假';


alter table sys_user add JXZJ varchar2(10);
alter table sys_user add NJQSRQ TIMESTAMP(6);

alter table sys_user_his add JXZJ varchar2(10);
alter table sys_user_his add NJQSRQ TIMESTAMP(6);

alter table sys_user_syn add JXZJ varchar2(10);
alter table sys_user_syn add NJQSRQ TIMESTAMP(6);

alter table hr_sys_user_syn add JXZJ varchar2(10);
alter table hr_sys_user_syn add NJQSRQ TIMESTAMP(6);