DROP SEQUENCE SEQ_SYS_ACL;
DROP SEQUENCE SEQ_SYS_CONFIG;
DROP SEQUENCE SEQ_SYS_DICT;
DROP SEQUENCE SEQ_SYS_DICT_DETAIL;
DROP SEQUENCE SEQ_SYS_MENU;
DROP SEQUENCE SEQ_SYS_ORG;
DROP SEQUENCE SEQ_SYS_ORG_USER;
DROP SEQUENCE SEQ_SYS_POSITION;
DROP SEQUENCE SEQ_SYS_RESOURCE;
DROP SEQUENCE SEQ_SYS_ROLE;
DROP SEQUENCE SEQ_SYS_ROLE_USER;
DROP SEQUENCE SEQ_SYS_USER;
DROP SEQUENCE SEQ_SYS_BIZ_LOG;
------------------------数据权限开始-----------------------------------
DROP SEQUENCE SEQ_SYS_PRV_BIZ_USER;
DROP SEQUENCE SEQ_SYS_PRV_AUTH_RESULT;
DROP SEQUENCE SEQ_SYS_PRV_ORG_AUTH;
DROP SEQUENCE SEQ_SYS_PRV_ROLE;
DROP SEQUENCE SEQ_SYS_PRV_ROLE_AUTH;
DROP SEQUENCE SEQ_SYS_PRV_ROLE_RESOURCE;
DROP SEQUENCE SEQ_SYS_PRV_TABLE_DEF;
DROP SEQUENCE SEQ_SYS_PRV_USER_SHARE;
------------------------数据权限结束-----------------------------------
DROP SEQUENCE SEQ_SYS_AREA;

DROP SEQUENCE SEQ_LOG_INFO;
DROP SEQUENCE SEQ_SYS_INDUSTRY;
DROP SEQUENCE SEQ_SYS_TEMPLATE;

-----------------------角色组管理---------------------------------------
DROP SEQUENCE SEQ_SYS_ROLE_GROUP;
DROP SEQUENCE SEQ_SYS_ROLE_GROUP_ROLE;

DROP SEQUENCE SEQ_SYS_VERSION;


DROP SEQUENCE SEQ_SYS_APP_FTP_INFO;
DROP SEQUENCE SEQ_SYS_APP_ERROR_INFO;

DROP SEQUENCE SEQ_SYS_USER_MSG_RELATION;
DROP SEQUENCE SEQ_SYS_MESSAGE;
----------------------请假---------------------------------------------
DROP SEQUENCE SEQ_SYS_LEAVE_INFO;
