/*
MySQL Backup
Source Server Version: 5.5.42
Source Database: ptdev
Date: 2016/11/14 15:05:05
*/

SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE JBPM4_EXECUTION DROP FOREIGN KEY FK_EXEC_INSTANCE;
ALTER TABLE JBPM4_EXECUTION ADD CONSTRAINT FK_EXEC_INSTANCE FOREIGN KEY (INSTANCE_) REFERENCES JBPM4_EXECUTION (DBID_) ON DELETE CASCADE ON UPDATE RESTRICT;

/*添加 主流程实例ID 字段*/
ALTER TABLE JBPM4_HIST_PROCINST ADD MAIN_ID_ VARCHAR(255) COMMENT '主流程实例ID';

/*添加 任务状态是否锁定标志*/
ALTER TABLE JBPM4_TASK ADD LOCK_STATE VARCHAR(2) DEFAULT 0 COMMENT '任务是否锁定(1:锁定,0:解锁)';

-- ----------------------------
--  TABLE STRUCTURE FOR `JBPM4_BIZ_OPTION_INFO`
-- ----------------------------
DROP TABLE IF EXISTS `JBPM4_BIZ_OPTION_INFO`;
CREATE TABLE `JBPM4_BIZ_OPTION_INFO` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FK_JBPM_BIZ_TAB_ID` VARCHAR(20) DEFAULT NULL,
  `PRO_INSTANCE_ID` VARCHAR(200) DEFAULT NULL,
  `TASK_ID` VARCHAR(20) DEFAULT NULL,
  `ACTIVE_NAME` VARCHAR(200) DEFAULT NULL,
  `SYSTEM_ACTIVE_INFO` VARCHAR(200) DEFAULT NULL,
  `OPTION_REMARK` VARCHAR(4000) DEFAULT NULL,
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL,
  `OWNER_ID` VARCHAR(20) DEFAULT NULL,
  `ORG_ID` VARCHAR(20) DEFAULT NULL,
  `CREATE_TIME` TIMESTAMP NULL DEFAULT NULL,
  `MODIFY_TIME` TIMESTAMP NULL DEFAULT NULL,
  `CREATE_BY` VARCHAR(20) DEFAULT NULL,
  `MODIFY_BY` VARCHAR(20) DEFAULT NULL,
  `REMARK` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=11 DEFAULT CHARSET=UTF8 COMMENT='业务流程节点意见表';

-- ----------------------------
--  TABLE STRUCTURE FOR `JBPM4_BIZ_TAB`
-- ----------------------------
DROP TABLE IF EXISTS `JBPM4_BIZ_TAB`;
CREATE TABLE `JBPM4_BIZ_TAB` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `BIZ_TAB_NAME` VARCHAR(200) DEFAULT NULL COMMENT '业务表名称',
  `BIZ_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '业务类型',
  `BIZ_INF_ID` VARCHAR(50) DEFAULT NULL COMMENT '业务表主键ID',
  `BIZ_INF_NAME` VARCHAR(500) DEFAULT NULL COMMENT '业务任务名称',
  `BIZ_TASK_TYPE` VARCHAR(2) DEFAULT NULL COMMENT '业务任务状态',
  `PRO_INSTANCE_ID` VARCHAR(200) NOT NULL COMMENT '主流程实例ID',
  `START_PRO_USERID` VARCHAR(20) DEFAULT NULL COMMENT '流程发起者',
  `PRO_INSTANCE_STATE` VARCHAR(2) DEFAULT '1' COMMENT '流程实例状态（1：正常，0：暂停）',
  `TASK_STATE` VARCHAR(2) DEFAULT NULL COMMENT '当前流程实例下的任务状态（0：解锁，1：加锁）',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '数据有效性（1：有效、0：无效）',
  `OWNER_ID` VARCHAR(20) DEFAULT NULL COMMENT '业务归属人',
  `ORG_ID` VARCHAR(20) DEFAULT NULL COMMENT '业务所属机构',
  `CREATE_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `MODIFY_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  `CREATE_BY` VARCHAR(20) DEFAULT NULL COMMENT '创建人',
  `MODIFY_BY` VARCHAR(20) DEFAULT NULL COMMENT '修改人',
  `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `IS_HIDDEN` VARCHAR(2) DEFAULT NULL,
  `BIZ_INF_NO` VARCHAR(100) DEFAULT NULL,
  `OVER_TIME` TIMESTAMP NULL DEFAULT NULL,
  `REMIND_TIME` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_JBPM4_BIZ_TAB_INF_NAME` (`BIZ_INF_NAME`(255))
) ENGINE=INNODB AUTO_INCREMENT=7 DEFAULT CHARSET=UTF8 COMMENT='工作流与业务表关联表';

-- ----------------------------
--  TABLE STRUCTURE FOR `JBPM4_CONSIGNED_TASK`
-- ----------------------------
DROP TABLE IF EXISTS `JBPM4_CONSIGNED_TASK`;
CREATE TABLE `JBPM4_CONSIGNED_TASK` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `TASK_ID` VARCHAR(50) DEFAULT NULL,
  `TASK_TYPE` VARCHAR(2) DEFAULT NULL,
  `FROM_USER_ID` VARCHAR(20) DEFAULT NULL,
  `TO_USER_ID` VARCHAR(20) DEFAULT NULL,
  `ORG_ID` VARCHAR(20) DEFAULT NULL,
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL,
  `CREATED_BY` VARCHAR(20) DEFAULT NULL,
  `CREATED` TIMESTAMP NULL DEFAULT NULL,
  `LAST_UPD_BY` VARCHAR(20) DEFAULT NULL,
  `LAST_UPD` TIMESTAMP NULL DEFAULT NULL,
  `REMARK` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='已经委托的任务表(同时记录任务部分转移轨迹)';

-- ----------------------------
--  TABLE STRUCTURE FOR `JBPM4_CONSIGN_PERSON`
-- ----------------------------
DROP TABLE IF EXISTS `JBPM4_CONSIGN_PERSON`;
CREATE TABLE `JBPM4_CONSIGN_PERSON` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FROM_USER_ID` VARCHAR(50) DEFAULT NULL,
  `TO_USER_ID` VARCHAR(50) DEFAULT NULL,
  `PRO_DEF_KEY` VARCHAR(200) DEFAULT NULL,
  `TYPE` VARCHAR(2) DEFAULT NULL,
  `REASON` VARCHAR(4000) DEFAULT NULL,
  `START_TIME` TIMESTAMP NULL DEFAULT NULL,
  `END_TIME` TIMESTAMP NULL DEFAULT NULL,
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL,
  `CREATED_BY` VARCHAR(20) DEFAULT NULL,
  `CREATED` TIMESTAMP NULL DEFAULT NULL,
  `LAST_UPD_BY` VARCHAR(20) DEFAULT NULL,
  `LAST_UPD` TIMESTAMP NULL DEFAULT NULL,
  `REMARK` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='设置任务委托表';

-- ----------------------------
--  TABLE STRUCTURE FOR `JBPM4_FORM_INFO`
-- ----------------------------
DROP TABLE IF EXISTS `JBPM4_FORM_INFO`;
CREATE TABLE `JBPM4_FORM_INFO` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `PRO_DEF_KEY` VARCHAR(500) DEFAULT NULL,
  `PRO_ACTIVITY_NAME` VARCHAR(500) DEFAULT NULL,
  `PRO_ACTIVITY_FORM` VARCHAR(500) DEFAULT NULL,
  `PARTICIPATOR_TYPE` VARCHAR(100) DEFAULT NULL,
  `PART_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '人工选择参与者时，配置的规则（1：机构，2：人员，0：角色）',
  `OTHER_PARAMS` VARCHAR(4000) DEFAULT NULL,
  `RULE_INFO` VARCHAR(4000) DEFAULT NULL,
  `CREATE_TIME` TIMESTAMP NULL DEFAULT NULL,
  `REMARK` VARCHAR(500) DEFAULT NULL,
  `EXT1` VARCHAR(500) DEFAULT NULL,
  `EXT2` VARCHAR(500) DEFAULT NULL,
  `EXT3` VARCHAR(500) DEFAULT NULL,
  `PRO_LEVEL` VARCHAR(20) DEFAULT NULL,
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=UTF8 COMMENT='工作流表单配置表';

-- ----------------------------
--  TABLE STRUCTURE FOR `JBPM4_ROLE_MAPPING`
-- ----------------------------
DROP TABLE IF EXISTS `JBPM4_ROLE_MAPPING`;
CREATE TABLE `JBPM4_ROLE_MAPPING` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `ROLE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '角色编码',
  `MAPPING_ROLE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '映射角色编码',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '数据有效性（1：有效、0：无效）',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='流程监控数据权限映射表';

-- ----------------------------
--  TABLE STRUCTURE FOR `JBPM4_RULE_INFO`
-- ----------------------------
DROP TABLE IF EXISTS `JBPM4_RULE_INFO`;
CREATE TABLE `JBPM4_RULE_INFO` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FK_RULE_ID` VARCHAR(50) DEFAULT NULL,
  `RULE_STATE` VARCHAR(2) DEFAULT NULL,
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL,
  `CREATED_BY` VARCHAR(20) DEFAULT NULL,
  `CREATED` TIMESTAMP NULL DEFAULT NULL,
  `LAST_UPD_BY` VARCHAR(20) DEFAULT NULL,
  `LAST_UPD` TIMESTAMP NULL DEFAULT NULL,
  `REMARK` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='工作流规则配置表';
-- ----------------------------
--  TABLE STRUCTURE FOR `TEMPORARY_JBPM4_INFO`
-- ----------------------------
DROP TABLE IF EXISTS `TEMPORARY_JBPM4_INFO`;
CREATE TABLE `TEMPORARY_JBPM4_INFO` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `XML_CONTENT` LONGTEXT,
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL,
  `LAST_UPD_BY` VARCHAR(20) DEFAULT NULL,
  `LAST_UPD` TIMESTAMP NULL DEFAULT NULL,
  `CREATED_BY` VARCHAR(20) DEFAULT NULL,
  `CREATED` TIMESTAMP NULL DEFAULT NULL,
  `REMARK` VARCHAR(500) DEFAULT NULL,
  `EXT1` VARCHAR(200) DEFAULT NULL,
  `PRO_PNG` LONGBLOB,
  `BIZ_FILE` VARCHAR(4000) DEFAULT NULL,
  `PROC_NAME` VARCHAR(4000) DEFAULT NULL,
  `PROC_CODE` VARCHAR(4000) DEFAULT NULL,
  `PROC_VERSION` VARCHAR(4000) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=27 DEFAULT CHARSET=UTF8 COMMENT='工作流暂存表';


DROP TRIGGER IF EXISTS `tri_jbpm4_hist_procinst`;
DELIMITER ;;
CREATE TRIGGER `tri_jbpm4_hist_procinst` BEFORE INSERT ON `jbpm4_hist_procinst` FOR EACH ROW /*
触发 保存 主流程实例id （main_id_）  信息
实现 结束的历史 主子流程信息查询
先查询 处其主流程实例id，有则保存，
否则　不保存
*/

begin

declare 	v_main_id       						varchar(255);
declare 	v_main_superexec_           bigint(20);
declare 	done           							int default 0;
declare		p_feeCode										varchar(20);
/*声明一个游标变量*/
declare  my_cur cursor for 
select t2.id_ from jbpm4_execution t2 where 1=1 
and exists(select 1 from jbpm4_execution t1 where t1.superexec_= t2.dbid_  and t1.id_ =new.id_);
/*申明循环结束的标志位 */
declare continue handler for not found set done=1;
set done=0; 


open my_cur;/*打开游标 */

loop_label:LOOP 
fetch my_cur into p_feeCode;/*将游标插入申明的变量 */
	if done = 1 then
		leave loop_label;
	else
		set v_main_id := p_feeCode;
		set new.main_id_ := v_main_id;
	end if; 

end LOOP;

close my_cur;/*循环结束后需要关闭游标 */
end
;;
DELIMITER ;


-- ----------------------------
--  Procedure definition for `updateProPng`
-- ----------------------------
DROP PROCEDURE IF EXISTS `updateProPng`;
DELIMITER ;;
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateProPng`(in id BIGINT(20),in contents LONGBLOB)
    COMMENT '发布流程成功后更新流程图片'
begin

	declare  v_pro_name varchar(100);
	declare  v_pro_ver	varchar(100);
	/*declare  v_content	LONGBLOB;*/

	select t2.proc_name ,t2.proc_version into v_pro_name ,v_pro_ver from temporary_jbpm4_info t2 where t2.id=id;

	update temporary_jbpm4_info t1
	set  t1.pro_png=''

	where  t1.proc_name=v_pro_name
	and t1.proc_version=v_pro_ver
	and t1.pro_png is not null ;
		 
	update temporary_jbpm4_info t1 set  t1.pro_png=contents where t1.id =id;
       
end
;;