/*
MYSQL BACKUP
SOURCE SERVER VERSION: 5.5.42
SOURCE DATABASE: PTDEV
DATE: 2016/11/14 14:53:10
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
--  TABLE STRUCTURE FOR `BIZ_CALENDAR`
-- ----------------------------
DROP TABLE IF EXISTS `BIZ_CALENDAR`;
CREATE TABLE `BIZ_CALENDAR` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `HOLIDAYS` VARCHAR(20) DEFAULT NULL COMMENT '假期（如：2014-09-10）',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '数据有效性（1：有效、0：无效）',
  `CREATED_BY` VARCHAR(20) DEFAULT NULL,
  `CREATED` DATETIME DEFAULT NULL,
  `LAST_UPD_BY` VARCHAR(20) DEFAULT NULL,
  `LAST_UPD` DATETIME DEFAULT NULL,
  `REMARK` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='假日表';

-- ----------------------------
--  TABLE STRUCTURE FOR `LEAVE_DEMO_INFO`
-- ----------------------------
DROP TABLE IF EXISTS `LEAVE_DEMO_INFO`;
CREATE TABLE `LEAVE_DEMO_INFO` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `APP_NAME` VARCHAR(50) DEFAULT NULL COMMENT '申请人姓名',
  `APP_REASON` VARCHAR(200) DEFAULT NULL COMMENT '请假原因',
  `APP_DAY` VARCHAR(20) DEFAULT NULL COMMENT '申请请假天数',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '数据有效性（1：有效、0：无效）',
  `APP_STATE` VARCHAR(20) DEFAULT NULL COMMENT '是否批准',
  `CREATE_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `MODIFY_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  `CREATE_BY` VARCHAR(20) DEFAULT NULL COMMENT '创建人',
  `MODIFY_BY` VARCHAR(20) DEFAULT NULL COMMENT '修改人',
  `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=UTF8 COMMENT='申请请假表';

-- ----------------------------
--  TABLE STRUCTURE FOR `LOAN_VMDATA_PRIV`
-- ----------------------------
DROP TABLE IF EXISTS `LOAN_VMDATA_PRIV`;
CREATE TABLE `LOAN_VMDATA_PRIV` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `USER_ID` BIGINT(18) DEFAULT NULL COMMENT '用户ID',
  `OWNER_ID` BIGINT(18) DEFAULT NULL COMMENT '数据归属人ID',
  `ORG_ID` BIGINT(18) DEFAULT NULL COMMENT '数据归属机构ID',
  `BIZ_ID` BIGINT(18) DEFAULT NULL COMMENT '业务表主键ID',
  `ORG_TYPE` VARCHAR(50) DEFAULT 'LOAN',
  `CREATE_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `CREATE_BY` BIGINT(18) DEFAULT NULL COMMENT '创建人',
  `VMRULE_MAPPING_ID` BIGINT(18) DEFAULT NULL COMMENT '映射表主键ID',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=UTF8 COMMENT='数据权限表';

-- ----------------------------
--  TABLE STRUCTURE FOR `LOAN_VMRULE_MAPPING`
-- ----------------------------
DROP TABLE IF EXISTS `LOAN_VMRULE_MAPPING`;
CREATE TABLE `LOAN_VMRULE_MAPPING` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `MAP_TYPE` VARCHAR(2) NOT NULL COMMENT '类型（1：人对人，2：人对机构，3：机构对机构）',
  `MAP_KEY` VARCHAR(20) NOT NULL COMMENT '关联KEY信息',
  `MAP_VALUE` VARCHAR(20) NOT NULL COMMENT '关联VALUE信息',
  `ORG_TYPE` VARCHAR(10) DEFAULT 'LOAN' COMMENT '虚拟树代码',
  `CREATE_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `CREATE_BY` BIGINT(18) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='映射表';

-- ----------------------------
--  TABLE STRUCTURE FOR `LOG_INFO`
-- ----------------------------
DROP TABLE IF EXISTS `LOG_INFO`;
CREATE TABLE `LOG_INFO` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  `USER_ID` VARCHAR(50) DEFAULT NULL COMMENT '用户ID',
  `MODULE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '模块名称',
  `CONTROLLER_NAME` VARCHAR(100) DEFAULT NULL COMMENT 'CONTROLLER名称',
  `METHOD_NAME` VARCHAR(100) DEFAULT NULL COMMENT '方法名称',
  `PARAM_INFO` VARCHAR(1000) DEFAULT NULL COMMENT '参数信息',
  `CREATED` DATE DEFAULT NULL COMMENT '生成日期',
  `URI` VARCHAR(200) DEFAULT NULL COMMENT '请求地址',
  `LOG_TYPE` VARCHAR(1) DEFAULT NULL COMMENT '日志类型0：访问日志，1：系统日志',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_ACL`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_ACL`;
CREATE TABLE `SYS_ACL` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ROLE_ID` BIGINT(18) DEFAULT NULL COMMENT '角色ID',
  `RESOURE_ID` BIGINT(18) DEFAULT NULL COMMENT '资源ID',
  `ACCESSIBILITY` INT(1) DEFAULT NULL COMMENT '1可访问，0拒绝访问',
  `APP_ID` BIGINT(18) DEFAULT NULL COMMENT '应用ID，备用',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT '1' COMMENT '有效性状态，1有效，0无效，默认1',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=249 DEFAULT CHARSET=UTF8 COMMENT='操作权限控制表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_AREA`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_AREA`;
CREATE TABLE `SYS_AREA` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `AREA_CODE` VARCHAR(50) DEFAULT NULL COMMENT '区域编码',
  `AREA_NAME` VARCHAR(100) DEFAULT NULL COMMENT '区域名称',
  `PARENT_ID` BIGINT(18) DEFAULT NULL COMMENT '父节点ID',
  `VALIDATE_STATE` VARCHAR(1) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=532928 DEFAULT CHARSET=UTF8 COMMENT='行政区域';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_ASYN_JOB`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_ASYN_JOB`;
CREATE TABLE `SYS_ASYN_JOB` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `BEAN_ID` VARCHAR(100) DEFAULT NULL COMMENT '业务实体BEANID',
  `BIZ_KEY_ID` VARCHAR(100) DEFAULT NULL COMMENT '业务表主键ID',
  `JOB_STATE` VARCHAR(2) DEFAULT NULL COMMENT '任务状态（1：待调用，0：已完成）',
  `START_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '任务调用开始时间',
  `END_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '任务调用结束时间',
  `ERROR_REMARK` VARCHAR(4000) DEFAULT NULL COMMENT '任务异常描述',
  `VALID` INT(2) DEFAULT NULL COMMENT '数据有效性(1：有效，0：无效)',
  `JOB_RUN` VARCHAR(2) DEFAULT NULL COMMENT '任务是否正在执行中 1：执行中，0:执行完成 或 未执行',
  `RUN_CUN` VARCHAR(200) DEFAULT NULL COMMENT '重复执行次数',
  `CREATE_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '数据新增时间',
  `REMARK` VARCHAR(2) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='异步接口任务表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_CONFIG`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_CONFIG`;
CREATE TABLE `SYS_CONFIG` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CONFIG_NAME` VARCHAR(100) DEFAULT NULL COMMENT '配置名称',
  `CONFIG_CODE` VARCHAR(100) DEFAULT NULL COMMENT '配置CODE',
  `CONFIG_VALUE` VARCHAR(4000) DEFAULT NULL,
  `CONFIG_TYPE` VARCHAR(100) DEFAULT NULL COMMENT '类型，0系统级（不可删除），1项目级',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=UTF8 COMMENT='系统配置表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_DICT`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_DICT`;
CREATE TABLE `SYS_DICT` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `DICT_CODE` VARCHAR(50) DEFAULT NULL COMMENT '数据字典CODE',
  `DICT_NAME` VARCHAR(50) DEFAULT NULL COMMENT '数据字典名称',
  `DICT_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '数据字典类型，0系统级（不可删除），1项目级',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=81 DEFAULT CHARSET=UTF8 COMMENT='数据字典';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_DICT_DETAIL`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_DICT_DETAIL`;
CREATE TABLE `SYS_DICT_DETAIL` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `DICT_ID` BIGINT(18) DEFAULT NULL COMMENT '主键字典主键',
  `DICT_DETAIL_NAME` VARCHAR(100) DEFAULT NULL COMMENT '数据名称',
  `DICT_DETAIL_VALUE` VARCHAR(500) DEFAULT NULL COMMENT '数据值',
  `ORDER_BY` VARCHAR(50) DEFAULT NULL COMMENT '排序',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=369 DEFAULT CHARSET=UTF8 COMMENT='数据字典明细表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_INDUSTRY`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_INDUSTRY`;
CREATE TABLE `SYS_INDUSTRY` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT,
  `INDUSTRY_NAME` VARCHAR(500) DEFAULT NULL COMMENT '行业名称/职位名称',
  `INDUSTRY_TYPE` VARCHAR(20) DEFAULT NULL COMMENT 'INDUSTRY:行业;POSITION:职位',
  `PARENT_CODE` VARCHAR(50) DEFAULT NULL COMMENT '职位所属的行(只对应职位数据有效)',
  `VALIDATE_STATE` VARCHAR(1) DEFAULT NULL,
  `INDUSTRY_CODE` VARCHAR(50) DEFAULT NULL COMMENT '行业、职位编码',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=928 DEFAULT CHARSET=UTF8 COMMENT='行业';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_LEAVE_INFO`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_LEAVE_INFO`;
CREATE TABLE `SYS_LEAVE_INFO` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `LEAVE_USER_ID` VARCHAR(20) DEFAULT NULL COMMENT '请假人ID',
  `USER_LEVEL` VARCHAR(200) DEFAULT NULL COMMENT '员工职级',
  `USER_NAME` VARCHAR(50) DEFAULT NULL COMMENT '员工姓名',
  `ORG_NAME` VARCHAR(200) DEFAULT NULL COMMENT '业务所属机构',
  `REASON` VARCHAR(500) DEFAULT NULL COMMENT '事由',
  `EMAIL` VARCHAR(100) DEFAULT NULL COMMENT '电子邮箱',
  `STATUS` VARCHAR(4) DEFAULT NULL COMMENT '状态（1：正常   2：请假中）',
  `START_TIME` DATE DEFAULT NULL COMMENT '请假开始时间',
  `END_TIME` DATE DEFAULT NULL COMMENT '请假结束时间',
  `LEAVE_TYPE` VARCHAR(2) DEFAULT NULL COMMENT '请假类型（1：代理请假，2：本人请假）',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '数据有效性（1：有效、0：无效）',
  `OWNER_ID` BIGINT(16) DEFAULT NULL COMMENT '业务归属人',
  `CREATE_TIME` TIMESTAMP NULL DEFAULT NULL  COMMENT '创建时间',
  `MODIFY_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  `CREATE_BY` BIGINT(16) DEFAULT NULL COMMENT '创建人',
  `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `MODIFY_BY` BIGINT(16) DEFAULT NULL COMMENT '修改人',
  `ORG_ID` BIGINT(18) DEFAULT NULL COMMENT '业务所属机构',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='员工请假表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_MENU`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_MENU`;
CREATE TABLE `SYS_MENU` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `MENU_CODE` VARCHAR(50) DEFAULT NULL COMMENT '菜单编码',
  `MENU_NAME` VARCHAR(50) DEFAULT NULL COMMENT '菜单名称',
  `MENU_ICON` VARCHAR(100) DEFAULT NULL COMMENT '菜单图标',
  `MENU_URL` VARCHAR(100) DEFAULT NULL COMMENT '菜单URL',
  `PARENT_ID` VARCHAR(50) DEFAULT NULL COMMENT '父菜单ID',
  `ORDER_BY` VARCHAR(50) DEFAULT NULL COMMENT '排序',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `APP_ID` BIGINT(18) DEFAULT NULL COMMENT '系统ID，备用',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  `RESOURCE_ID` INT(22) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=49 DEFAULT CHARSET=UTF8 COMMENT='菜单管理表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_MESSAGE`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_MESSAGE`;
CREATE TABLE `SYS_MESSAGE` (
  `MSG_ID` INT(20) NOT NULL AUTO_INCREMENT COMMENT '唯一标识，主键',
  `TITLE` VARCHAR(100) DEFAULT NULL COMMENT '消息标题',
  `BODY` VARCHAR(1000) DEFAULT NULL COMMENT '消息体',
  `URL` VARCHAR(300) DEFAULT NULL COMMENT '消息链接，可为空',
  `CREATE_DATE` DATE DEFAULT NULL COMMENT '消息创建日期',
  `START_DATE` DATE DEFAULT NULL COMMENT '消息生效日期',
  `END_DATE` DATE DEFAULT NULL COMMENT '消息失效日期',
  `STATUS` CHAR(1) DEFAULT NULL COMMENT '信息状态 0：初始；1：生效；2：失效；3：删除；DEFAULT：0',
  `PUBLISHER` VARCHAR(10) DEFAULT NULL COMMENT '消息发布者ID',
  `TYPE` CHAR(1) DEFAULT NULL COMMENT '信息的类型 0：全局消息；1：专有消息',
  `CHARSET` VARCHAR(10) DEFAULT NULL COMMENT '信息体的编码集',
  `URGENT_FLAG` CHAR(1) DEFAULT NULL COMMENT '紧急标识 0:普通；1：紧急；2：特急 DEFAULT:0',
  `SYS_FLAG` VARCHAR(6) DEFAULT NULL COMMENT '标识归属于哪个系统；可取值范围：7/1/2/4/5/6/3，取值规则：TYPE为0时该字段为111；001标识贷前；010标识贷后；100标识财富；以此类推101标识贷前和财富',
  PRIMARY KEY (`MSG_ID`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=UTF8 COMMENT='站内消息';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_MESSAGE_HIS`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_MESSAGE_HIS`;
CREATE TABLE `SYS_MESSAGE_HIS` (
  `MSG_ID` INT(20) NOT NULL AUTO_INCREMENT COMMENT '唯一标识，主键',
  `TITLE` VARCHAR(100) DEFAULT NULL COMMENT '消息标题',
  `BODY` VARCHAR(1000) DEFAULT NULL COMMENT '消息体',
  `URL` VARCHAR(300) DEFAULT NULL COMMENT '消息链接，可为空',
  `CREATE_DATE` DATE DEFAULT NULL COMMENT '消息创建日期',
  `START_DATE` DATE DEFAULT NULL COMMENT '消息生效日期',
  `END_DATE` DATE DEFAULT NULL COMMENT '消息失效日期',
  `STATUS` CHAR(1) DEFAULT NULL COMMENT '信息状态 0：初始；1：生效；2：失效；3：删除；DEFAULT：0',
  `PUBLISHER` VARCHAR(10) DEFAULT NULL COMMENT '消息发布者ID',
  `TYPE` CHAR(1) DEFAULT NULL COMMENT '信息的类型 0：全局消息；1：专有消息',
  `CHARSET` VARCHAR(10) DEFAULT NULL COMMENT '信息体的编码集',
  `URGENT_FLAG` CHAR(1) DEFAULT NULL COMMENT '紧急标识 0:普通；1：紧急；2：特急 DEFAULT:0',
  `SYS_FLAG` VARCHAR(6) DEFAULT NULL COMMENT '标识归属于哪个系统；可取值范围：7/1/2/4/5/6/3，取值规则：TYPE为0时该字段为111；001标识贷前；010标识贷后；100标识财富；以此类推101标识贷前和财富',
  PRIMARY KEY (`MSG_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_ORG`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_ORG`;
CREATE TABLE `SYS_ORG` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '机构ID',
  `ORG_CODE` VARCHAR(100) DEFAULT NULL COMMENT '机构编码',
  `ORG_NAME` VARCHAR(100) DEFAULT NULL COMMENT '机构名称',
  `ORG_TYPE` VARCHAR(10) DEFAULT NULL COMMENT '机构类型：ORG组织，DEPT部门',
  `PARENT_ID` VARCHAR(100) DEFAULT NULL COMMENT '父机构ID',
  `PARENT_IDS` VARCHAR(1000) DEFAULT NULL COMMENT '父机构ID串，以/分割',
  `ORDER_BY` VARCHAR(50) DEFAULT NULL COMMENT '排序',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `IS_VIRTUAL` VARCHAR(1) DEFAULT NULL COMMENT '是否是虚拟组织，1是，0否，默认0',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  `APP_FLAG` VARCHAR(10) DEFAULT NULL COMMENT '应用标志',
  `IS_LEEF` VARCHAR(1) DEFAULT NULL COMMENT '是否叶子节点',
  `AREA_CODES` VARCHAR(50) DEFAULT NULL COMMENT '区域编码',
  `AREA_ADRESS` VARCHAR(50) DEFAULT NULL COMMENT '区域名称',
  `ORG_LEVEL` INT(2) DEFAULT NULL COMMENT '层级',
  `EFFECTIVE_DATE` TIMESTAMP NULL DEFAULT NULL COMMENT '生效期',
  `CREATE_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建日期',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=102103 DEFAULT CHARSET=UTF8 COMMENT='机构部门表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_ORG_USER`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_ORG_USER`;
CREATE TABLE `SYS_ORG_USER` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ORG_ID` BIGINT(18) DEFAULT NULL COMMENT '机构ID',
  `USER_ID` BIGINT(18) DEFAULT NULL COMMENT '用户ID',
  `POSITION_ID` BIGINT(18) DEFAULT NULL COMMENT '岗位ID',
  `IS_MAIN_ORG` VARCHAR(1) DEFAULT NULL COMMENT '是否主部门，1是（主部门），0否（兼职部门），默认1',
  `VALIDATE_STATE` VARCHAR(1) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  `POSITION_CODE` VARCHAR(50) DEFAULT NULL COMMENT '岗位编码',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8 COMMENT='员工归属机构部门表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_POSITION`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_POSITION`;
CREATE TABLE `SYS_POSITION` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `POSITION_NAME` VARCHAR(18) DEFAULT NULL COMMENT '岗位名称',
  `POSITION_CODE` VARCHAR(50) DEFAULT NULL COMMENT '岗位编码',
  `ORDER_BY` VARCHAR(50) DEFAULT NULL COMMENT '排序',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  `CREATE_DATE` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `ORG_CODE` VARCHAR(20) DEFAULT NULL COMMENT '所属机构编码',
  `IS_RESPONSIBLE` INT(2) DEFAULT NULL COMMENT '是否负责,1是,0否',
  `POSITION_SEQUENCE` INT(2) DEFAULT NULL COMMENT '岗位序列,1管理序列,2职能序列,3业务序列,4技术序列,5运营序列',
  `POST` VARCHAR(50) DEFAULT NULL COMMENT '职位',
  `EFFECTIVE_DATE` TIMESTAMP NULL DEFAULT NULL COMMENT '生效时间',
  `PARENT_ID` VARCHAR(19) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=260 DEFAULT CHARSET=UTF8 COMMENT='岗位定义表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_PRV_AUTH_RESULT`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_PRV_AUTH_RESULT`;
CREATE TABLE `SYS_PRV_AUTH_RESULT` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_ID_FROM` BIGINT(18) DEFAULT NULL COMMENT '授权用户ID',
  `USER_ID_TO` BIGINT(18) DEFAULT NULL COMMENT '被授权用户ID',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性',
  `INSERT_FROM` VARCHAR(18) DEFAULT NULL COMMENT '数据来源是哪个表。S是用户共享表，O是组织机构表，R是角色表。多个来源以'',''分开',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='数据权限授权结果表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_PRV_BIZ_USER`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_PRV_BIZ_USER`;
CREATE TABLE `SYS_PRV_BIZ_USER` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_ID` BIGINT(18) DEFAULT NULL COMMENT '用户ID',
  `ORG_ID` BIGINT(18) DEFAULT NULL COMMENT '机构ID',
  `BIZ_ID` BIGINT(18) DEFAULT NULL COMMENT '业务ID',
  `TABLE_NAME` VARCHAR(50) DEFAULT NULL COMMENT '业务表名',
  `ACTION_STATE` VARCHAR(2) DEFAULT NULL COMMENT '操作状态，插入I，删除D',
  `SYN_STATE` VARCHAR(2) DEFAULT NULL COMMENT '同步状态，未同步0，已同步1',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效状态，1有效，0无效，默认1',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='权限注册表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_PRV_ORG_AUTH`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_PRV_ORG_AUTH`;
CREATE TABLE `SYS_PRV_ORG_AUTH` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_ID` BIGINT(18) DEFAULT NULL COMMENT '用户ID',
  `ORG_ID` BIGINT(18) DEFAULT NULL COMMENT '组织ID',
  `ACTION_STATE` VARCHAR(2) DEFAULT NULL COMMENT '操作状态，插入I，删除D',
  `SYN_STATE` VARCHAR(2) DEFAULT NULL COMMENT '同步状态，未同步0，已同步1',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效状态，1有效，0无效，默认1',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='组织授权表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_PRV_ROLE`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_PRV_ROLE`;
CREATE TABLE `SYS_PRV_ROLE` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ROLE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '角色CODE',
  `ROLE_NAME` VARCHAR(50) DEFAULT NULL COMMENT '角色名称',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='数据权限角色定义';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_PRV_ROLE_AUTH`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_PRV_ROLE_AUTH`;
CREATE TABLE `SYS_PRV_ROLE_AUTH` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_ID` BIGINT(18) DEFAULT NULL COMMENT '用户ID',
  `ROLE_ID` BIGINT(18) DEFAULT NULL COMMENT '角色ID',
  `ACTION_STATE` VARCHAR(2) DEFAULT NULL COMMENT '操作状态，插入I，删除D',
  `SYN_STATE` VARCHAR(2) DEFAULT NULL COMMENT '同步状态，未同步0，已同步1',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效状态，1有效，0无效，默认1',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='数据权限角色授权表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_PRV_ROLE_RESOURCE`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_PRV_ROLE_RESOURCE`;
CREATE TABLE `SYS_PRV_ROLE_RESOURCE` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ROLE_ID` BIGINT(18) DEFAULT NULL COMMENT '角色ID',
  `RESOURCE_ID` BIGINT(18) DEFAULT NULL COMMENT '资源ID',
  `RESOURCE_TYPE` VARCHAR(10) DEFAULT NULL COMMENT '资源类型，机构ORG，用户USER',
  `ACTION_STATE` VARCHAR(2) DEFAULT NULL COMMENT '操作状态，插入I，删除D',
  `SYN_STATE` VARCHAR(2) DEFAULT NULL COMMENT '同步状态，未同步0，已同步1',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效状态，1有效，0无效，默认1',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='数据角色资源表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_PRV_TABLE_DEF`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_PRV_TABLE_DEF`;
CREATE TABLE `SYS_PRV_TABLE_DEF` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `TABLE_NAME` VARCHAR(50) DEFAULT NULL COMMENT '表名称',
  `TABLE_DESC` VARCHAR(500) DEFAULT NULL COMMENT '描述',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性，1有效，0无效，默认1',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNI_SYS_DATA_PRV_TABLE` (`TABLE_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='数据权限表定义';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_PRV_USER_SHARE`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_PRV_USER_SHARE`;
CREATE TABLE `SYS_PRV_USER_SHARE` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `FROM_USER_ID` BIGINT(18) DEFAULT NULL COMMENT '共享用户ID',
  `TO_USER_ID` BIGINT(18) DEFAULT NULL COMMENT '被共享用户ID',
  `ACTION_STATE` VARCHAR(2) DEFAULT NULL COMMENT '操作状态，插入I，删除D',
  `SYN_STATE` VARCHAR(2) DEFAULT NULL COMMENT '同步状态，未同步0，已同步1',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效状态，1有效，0无效，默认1',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='数据共享表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_RESOURCE`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_RESOURCE`;
CREATE TABLE `SYS_RESOURCE` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `RESOURE_NAME` VARCHAR(200) DEFAULT NULL COMMENT '名称',
  `RESOURE_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '类型，URL或BUTTON',
  `RESOURE_URL` VARCHAR(200) DEFAULT NULL COMMENT 'URL地址',
  `PERMISSION` VARCHAR(200) DEFAULT NULL COMMENT '权限标识',
  `PARENT_ID` VARCHAR(50) DEFAULT NULL COMMENT '父ID',
  `PARENT_IDS` VARCHAR(200) DEFAULT NULL COMMENT '父ID串，以/分割',
  `APP_ID` BIGINT(18) DEFAULT NULL COMMENT '应用ID，备用字段',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=59 DEFAULT CHARSET=UTF8 COMMENT='角色表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_ROLE`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_ROLE`;
CREATE TABLE `SYS_ROLE` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ROLE_NAME` VARCHAR(50) DEFAULT NULL COMMENT '角色名称',
  `ROLE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '角色编码',
  `ROLE_TYPE` VARCHAR(1) DEFAULT NULL COMMENT '角色类型：0系统角色（不能删除），1项目自定义角色',
  `APP_ID` BIGINT(18) DEFAULT NULL COMMENT '系统ID，备用',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=6 DEFAULT CHARSET=UTF8;

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_ROLE_GROUP`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_ROLE_GROUP`;
CREATE TABLE `SYS_ROLE_GROUP` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ROLE_GROUP_NAME` VARCHAR(100) DEFAULT NULL,
  `ROLE_GROUP_CODE` VARCHAR(50) DEFAULT NULL COMMENT '角色组编码',
  `ROLE_GROUP_TYPE` VARCHAR(1) DEFAULT NULL COMMENT '角色组类型：备用，默认1',
  `APP_ID` BIGINT(18) DEFAULT NULL COMMENT '系统ID，备用',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=UTF8 COMMENT='角色组';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_ROLE_GROUP_ROLE`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_ROLE_GROUP_ROLE`;
CREATE TABLE `SYS_ROLE_GROUP_ROLE` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ROLE_ID` BIGINT(18) DEFAULT NULL COMMENT '角色ID',
  `ROLE_GROUP_ID` BIGINT(18) DEFAULT NULL COMMENT '角色组ID',
  `APP_ID` BIGINT(18) DEFAULT NULL COMMENT '系统ID，备用',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `VERSION` BIGINT(18) DEFAULT NULL COMMENT '乐观锁',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=UTF8 COMMENT='角色组角色中间表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_ROLE_USER`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_ROLE_USER`;
CREATE TABLE `SYS_ROLE_USER` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ROLE_ID` BIGINT(18) DEFAULT NULL COMMENT '角色ID',
  `TARGET_ID` BIGINT(18) DEFAULT NULL COMMENT '用户ID或者机构ID',
  `APP_ID` BIGINT(18) DEFAULT NULL COMMENT '系统ID，备用',
  `TARGET_TYPE` VARCHAR(50) DEFAULT NULL COMMENT 'USER用户类型,ORG机构类型',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=6 DEFAULT CHARSET=UTF8 COMMENT='角色用户表';


-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_TEMPLATE`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_TEMPLATE`;
CREATE TABLE `SYS_TEMPLATE` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '机构ID',
  `APP_ID` VARCHAR(50) DEFAULT NULL COMMENT '系统ID',
  `TEMPLATE_NO` VARCHAR(50) DEFAULT NULL COMMENT '模板编码',
  `TEMPLATE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '模板名称',
  `TEMPLATE_TYPE` VARCHAR(2) DEFAULT NULL COMMENT '模板类型 1  短信 2邮件 9 其他',
  `TEMPLATE_CONTENT` LONGBLOB COMMENT '模板内容',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=6 DEFAULT CHARSET=UTF8 COMMENT='模板';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_USER`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE `SYS_USER` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_NAME` VARCHAR(50) DEFAULT NULL COMMENT '姓名',
  `USER_NO` VARCHAR(50) DEFAULT NULL COMMENT '编码',
  `LOGIN_NAME` VARCHAR(50) DEFAULT NULL COMMENT '登录名',
  `PASSWORD` VARCHAR(50) DEFAULT NULL COMMENT '登录密码',
  `SALT` VARCHAR(50) DEFAULT NULL COMMENT '盐值',
  `MOBILE` VARCHAR(50) DEFAULT NULL COMMENT '手机',
  `EMAIL` VARCHAR(50) DEFAULT NULL COMMENT '邮件',
  `USER_IMAGE` VARCHAR(100) DEFAULT NULL COMMENT '用户头像',
  `SEX` VARCHAR(50) DEFAULT NULL COMMENT '性别',
  `BIRTHDAY` VARCHAR(50) DEFAULT NULL COMMENT '出生日期',
  `NATIONALITY` VARCHAR(50) DEFAULT NULL COMMENT '民族',
  `EDUCATION` VARCHAR(50) DEFAULT NULL COMMENT '学历',
  `JOB` VARCHAR(100) DEFAULT NULL COMMENT '职务',
  `HOME_ADDRESS` VARCHAR(100) DEFAULT NULL COMMENT '家庭住址',
  `HOME_ZIPCODE` VARCHAR(50) DEFAULT NULL COMMENT '家庭邮编',
  `HOME_TEL` VARCHAR(50) DEFAULT NULL COMMENT '家庭电话',
  `OFFICE_TEL` VARCHAR(50) DEFAULT NULL COMMENT '办公电话',
  `OFFICE_ADDRESS` VARCHAR(100) DEFAULT NULL COMMENT '办公地址',
  `ORDER_BY` VARCHAR(50) DEFAULT NULL COMMENT '排序',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '有效性状态，1有效，0无效，默认1',
  `IS_LOCKED` VARCHAR(2) DEFAULT NULL COMMENT '是否锁定，1锁定，0未锁，默认0',
  `VERSION` BIGINT(16) DEFAULT NULL COMMENT '乐观锁',
  `PROBATION_PERIOD` INT(2) DEFAULT NULL,
  `ENTRY_DATE` TIMESTAMP NULL DEFAULT NULL COMMENT '入职日期',
  `QUIT_DATE` TIMESTAMP NULL DEFAULT NULL COMMENT '离职日期',
  `WORK_DATE` TIMESTAMP NULL DEFAULT NULL COMMENT '参加工作日期',
  `POLITICAL_STATUS` VARCHAR(2) DEFAULT '' COMMENT '政治面貌,1党员,2团员,3群众,4民主党派,5预备党员',
  `USER_RELATION` VARCHAR(20) DEFAULT NULL COMMENT '员工关系,1正式,2试用,3实习,4劳务派遣',
  `CREATE_DATE` TIMESTAMP NULL DEFAULT NULL COMMENT '创建日期',
  `CARD_NO` VARCHAR(50) DEFAULT NULL COMMENT '证件号码',
  `ANNUAL_LEAVE` INT(2) DEFAULT NULL COMMENT '标准年假',
  `JXZJ` VARCHAR(10) DEFAULT NULL,
  `NJQSRQ` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_SYS_USER_LOGIN_NAME` (`LOGIN_NAME`)
) ENGINE=INNODB AUTO_INCREMENT=10005267 DEFAULT CHARSET=UTF8 COMMENT='系统用户表';

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_USER_MSG_RELATION`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_USER_MSG_RELATION`;
CREATE TABLE `SYS_USER_MSG_RELATION` (
  `REL_ID` INT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `REL_STATUS` CHAR(1) DEFAULT NULL COMMENT '信息状态：0：有效1：用户删除；DEFAULT0',
  `USER_ID` VARCHAR(10) DEFAULT NULL COMMENT '归属者ID',
  `READ_FLAG` CHAR(1) DEFAULT NULL COMMENT '用户读取状态：0:未读；1：已读 DEFAULT:0',
  `MSG_ID` INT(20) DEFAULT NULL COMMENT '消息ID',
  PRIMARY KEY (`REL_ID`)
) ENGINE=INNODB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8;

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_USER_MSG_RELATION_HIS`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_USER_MSG_RELATION_HIS`;
CREATE TABLE `SYS_USER_MSG_RELATION_HIS` (
  `REL_ID` INT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `REL_STATUS` CHAR(1) DEFAULT NULL COMMENT '信息状态：0：有效1：用户删除；DEFAULT0',
  `USER_ID` VARCHAR(10) DEFAULT NULL COMMENT '归属者ID',
  `READ_FLAG` CHAR(1) DEFAULT NULL COMMENT '用户读取状态：0:未读；1：已读 DEFAULT:0',
  `MSG_ID` INT(20) DEFAULT NULL COMMENT '消息ID',
  PRIMARY KEY (`REL_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- ----------------------------
--  TABLE STRUCTURE FOR `SYS_VERSION`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_VERSION`;
CREATE TABLE `SYS_VERSION` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `VERSION_NUM` VARCHAR(50) DEFAULT NULL COMMENT '版本号',
  `VERSION_NAME` VARCHAR(200) DEFAULT NULL COMMENT '版本名称',
  `VERSION_CONTENT` VARCHAR(4000) DEFAULT NULL COMMENT '版本内容',
  `VERSION_TIME` VARCHAR(50) DEFAULT NULL COMMENT '上线时间',
  `SYSTEM_STATE` VARCHAR(50) DEFAULT NULL COMMENT '系统标志位',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='系统版本号表';

-- ----------------------------
--  TABLE STRUCTURE FOR `VMAUTH_REGISTER_INFO`
-- ----------------------------
DROP TABLE IF EXISTS `VMAUTH_REGISTER_INFO`;
CREATE TABLE `VMAUTH_REGISTER_INFO` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `VMTREE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '虚拟树代码',
  `VMTREE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '虚拟树名称',
  `MAP_TAB_NAME` VARCHAR(100) DEFAULT NULL COMMENT '映射表名',
  `DATA_TAB_NAME` VARCHAR(100) DEFAULT NULL COMMENT '数据权限表名',
  `MAP_INIT_SQL` VARCHAR(4000) DEFAULT NULL COMMENT '映射表创建SQL',
  `DATA_INIT_SQL` VARCHAR(4000) DEFAULT NULL COMMENT '数据权限表创建SQL',
  `CREATE_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `CREATE_BY` BIGINT(18) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=12 DEFAULT CHARSET=UTF8;

-- ----------------------------
--  TABLE STRUCTURE FOR `VMTREE_INFO`
-- ----------------------------
DROP TABLE IF EXISTS `VMTREE_INFO`;
CREATE TABLE `VMTREE_INFO` (
  `ORG_ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '序列或HR的ORGID',
  `ORG_NAME` VARCHAR(200) DEFAULT NULL COMMENT '机构名称',
  `ORG_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '虚拟树代码',
  `PARENT_ID` BIGINT(18) DEFAULT NULL COMMENT '父节点ORG_ID',
  `SOURCE_TYPE` VARCHAR(10) DEFAULT NULL COMMENT '数据来源（XN/HR）',
  `END_FLAG` VARCHAR(2) DEFAULT NULL COMMENT '是否叶子节点（1：是，0：否）',
  `CREATE_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `CREATE_BY` BIGINT(18) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`ORG_ID`)
) ENGINE=INNODB AUTO_INCREMENT=7 DEFAULT CHARSET=UTF8 COMMENT='虚拟树表';

-- ----------------------------
--  TABLE STRUCTURE FOR `VMUSER_VMORG_MAP`
-- ----------------------------
DROP TABLE IF EXISTS `VMUSER_VMORG_MAP`;
CREATE TABLE `VMUSER_VMORG_MAP` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `USER_ID` BIGINT(18) DEFAULT NULL COMMENT '用户ID',
  `ORG_ID` BIGINT(18) DEFAULT NULL COMMENT '虚拟树的ORG_ID',
  `ORG_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '虚拟树代码',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=UTF8 COMMENT='员工虚拟组织关系表';

DROP VIEW IF EXISTS `SYS_DATA_PRV`;
CREATE  VIEW `SYS_DATA_PRV` AS SELECT  T1.TABLE_NAME,T1.BIZ_ID,T1.USER_ID AS CREATE_USER_ID,T2.USER_ID_FROM AS AUTH_USER_ID FROM SYS_PRV_BIZ_USER T1, SYS_PRV_AUTH_RESULT  T2 WHERE T2.USER_ID_TO=T1.USER_ID ;


INSERT INTO `vmtree_info` VALUES ('1','LOAN7','LOAN7','0','XN',NULL,'2016-10-28 13:12:29','1'), ('2','LOAN','LOAN','0','XN',NULL,'2016-10-28 13:29:55','1'), ('3','111','LOAN','2','XN','','2016-10-28 14:08:22','1'), ('4','222','LOAN','3','XN','','2016-10-28 14:08:31','1'), ('5','333','LOAN','3','XN','','2016-10-28 14:09:40','1'), ('6','总公司','LOAN','2','HR','0','2016-10-28 16:36:51','1');
