/*
MYSQL BACKUP
SOURCE SERVER VERSION: 5.5.42
SOURCE DATABASE: PTDEV
DATE: 2016/11/14 15:01:28
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
--  TABLE STRUCTURE FOR `QUARTZ_TASK_GROUP_DEF`
-- ----------------------------
DROP TABLE IF EXISTS `QUARTZ_TASK_GROUP_DEF`;
CREATE TABLE `QUARTZ_TASK_GROUP_DEF` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `GROUP_ID` VARCHAR(50) DEFAULT NULL COMMENT '分组处理编号',
  `GROUP_NAME` VARCHAR(40) DEFAULT NULL COMMENT '分组处理名称',
  `GROUP_STATE` VARCHAR(40) DEFAULT NULL COMMENT '分组任务是否发布（1：发布，0：待发布）',
  `TASK_ID` VARCHAR(20) NOT NULL COMMENT '任务编号',
  `TASK_NAME` VARCHAR(100) DEFAULT NULL COMMENT '任务描述',
  `BEAN_ID` VARCHAR(100) DEFAULT NULL COMMENT '任务类名（实体BEANID）',
  `DEAL_STEP` BIGINT(8) DEFAULT NULL COMMENT '执行步骤(顺序序号)',
  `PRE_STEP` VARCHAR(100) DEFAULT NULL COMMENT '前提步骤（任务编号）',
  `PRE_STEP_STATE` VARCHAR(2) DEFAULT NULL COMMENT '前置步骤返回状态（1：成功，0：是失败）',
  `AUTO_EXEC` VARCHAR(2) DEFAULT NULL COMMENT '是否自动执行（1：自动，0：手动）',
  `DEAL_CHANCE` VARCHAR(10) DEFAULT NULL COMMENT '执行时机（DAY:每天，YEAR：每年12月31日，NORUN:不执行）',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '数据有效性（1：有效、0：无效）',
  `CREATED_BY` VARCHAR(20) DEFAULT NULL COMMENT '新增人',
  `CREATED` TIMESTAMP NULL DEFAULT NULL COMMENT '新增时间',
  `LAST_UPD_BY` VARCHAR(20) DEFAULT NULL COMMENT '修改人',
  `LAST_UPD` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `RUN_TIME` VARCHAR(10) DEFAULT NULL COMMENT '执行时间',
  `IS_END` VARCHAR(1) DEFAULT '0' COMMENT '是否执行',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='任务分组定义表';

-- ----------------------------
--  TABLE STRUCTURE FOR `QUARTZ_TASK_GROUP_INSTANCE`
-- ----------------------------
DROP TABLE IF EXISTS `QUARTZ_TASK_GROUP_INSTANCE`;
CREATE TABLE `QUARTZ_TASK_GROUP_INSTANCE` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `GROUP_ID` VARCHAR(50) DEFAULT NULL COMMENT '分组处理编号',
  `GROUP_NAME` VARCHAR(40) DEFAULT NULL COMMENT '分组处理名称',
  `BATCH_NO` VARCHAR(40) DEFAULT NULL COMMENT '批次号码',
  `TASK_ID` VARCHAR(20) NOT NULL COMMENT '任务编号',
  `TASK_NAME` VARCHAR(100) DEFAULT NULL COMMENT '任务描述',
  `BEAN_ID` VARCHAR(100) DEFAULT NULL COMMENT '任务类名（实体BEANID）',
  `DEAL_STEP` BIGINT(8) DEFAULT NULL COMMENT '执行步骤(顺序序号)',
  `PRE_STEP` VARCHAR(100) DEFAULT NULL COMMENT '前提步骤（任务编号）',
  `PRE_STEP_STATE` VARCHAR(2) DEFAULT NULL COMMENT '前置步骤返回状态（1：成功，0：是失败）',
  `AUTO_EXEC` VARCHAR(2) DEFAULT NULL COMMENT '是否自动执行（1：自动，0：手动）',
  `DEAL_CHANCE` VARCHAR(10) DEFAULT NULL COMMENT '执行时机（DAY:每天，YEAR：每年12月31日，NORUN:不执行）',
  `TASK_INS_STATE` VARCHAR(2) DEFAULT NULL COMMENT '任务实例执行状态（1：成功：0：失败）',
  `BUG_CONTINUE` VARCHAR(2) DEFAULT NULL COMMENT '失败后，断点执行（1：是，0：否）',
  `IS_END` VARCHAR(2) DEFAULT NULL COMMENT '任务是否执行（0：执行，1：未执行）',
  `VALIDATE_STATE` VARCHAR(2) DEFAULT NULL COMMENT '数据有效性（1：有效、0：无效）',
  `CREATED` TIMESTAMP NULL DEFAULT NULL COMMENT '新增时间',
  `LAST_UPD` DATETIME DEFAULT NULL COMMENT '修改时间',
  `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `PERSON_SET_START_TIME` VARCHAR(50) DEFAULT NULL COMMENT '人工设置的手动执行时间（如：2014-10-10 10:10:00）',
  `TASK_START_TIME` VARCHAR(20) DEFAULT NULL COMMENT '任务开始时间',
  `TASK_END_TIME` VARCHAR(20) DEFAULT NULL COMMENT '任务结束时间',
  `FAIL_TIMES` DECIMAL(8,0) DEFAULT '0' COMMENT '失败次数',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='任务分组实例表';

-- ----------------------------
--  TABLE STRUCTURE FOR `QUARTZ_TASK_HCOMMENT`
-- ----------------------------
DROP TABLE IF EXISTS `QUARTZ_TASK_HCOMMENT`;
CREATE TABLE `QUARTZ_TASK_HCOMMENT` (
  `ID` BIGINT(18) NOT NULL COMMENT '主键ID',
  `BATCH_NO` VARCHAR(50) DEFAULT NULL COMMENT '批次号码',
  `GROUP_ID` VARCHAR(50) DEFAULT NULL COMMENT '分组编码',
  `THREAD_ID` VARCHAR(50) DEFAULT NULL COMMENT '执行任务的主线程ID',
  `TASK_ID` VARCHAR(20) NOT NULL COMMENT '任务编号',
  `BEAN_ID` VARCHAR(100) DEFAULT NULL COMMENT '任务类名（实体BEANID）',
  `TASK_STATE` VARCHAR(2) DEFAULT NULL COMMENT '任务执行返回结果（1：成功，0：是失败）',
  `TASK_START_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '任务执行开始时间',
  `TASK_END_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '任务执行结束时间',
  `TASK_INFO` VARCHAR(4000) DEFAULT NULL COMMENT '任务执行中信息描述',
  `ERROR_INFO` VARCHAR(4000) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='定时任务执行轨迹表';

-- ----------------------------
--  TABLE STRUCTURE FOR `QUARTZ_TASK_HIS`
-- ----------------------------
DROP TABLE IF EXISTS `QUARTZ_TASK_HIS`;
CREATE TABLE `QUARTZ_TASK_HIS` (
  `ID` BIGINT(18) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `BATCH_NO` VARCHAR(50) DEFAULT NULL COMMENT '批次号码',
  `GROUP_ID` VARCHAR(50) DEFAULT NULL COMMENT '分组编码',
  `THREAD_ID` VARCHAR(50) DEFAULT NULL COMMENT '执行任务的主线程ID',
  `TASK_ID` VARCHAR(20) NOT NULL COMMENT '任务编号',
  `BEAN_ID` VARCHAR(100) DEFAULT NULL COMMENT '任务类名（实体BEANID）',
  `TASK_STATE` VARCHAR(2) DEFAULT NULL COMMENT '任务执行返回结果（1：成功，0：是失败）',
  `TASK_START_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '任务执行开始时间',
  `TASK_END_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '任务执行结束时间',
  `TASK_INFO` VARCHAR(4000) DEFAULT NULL COMMENT '任务执行中信息描述',
  `ERROR_INFO` VARCHAR(4000) DEFAULT NULL COMMENT '任务执行失败，错误描述',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='定时任务执行轨迹表';

-- ----------------------------
--  RECORDS 
-- ----------------------------
